### ISSUE TITLE
non CLI - Handlebars version not synced with Metalsmith

### ISSUE THREAD

**Issue by iabw** [linclark/metalsmith-register-partials#1]
In trying to use from a Metalsmith script ( instead of the CLI reading from metalsmith.json, which I assume just works correctly ), I am getting the error "The partial header could not be found".

This is what the script I'm running looks like:

```
var Metalsmith  = require('metalsmith'),
    markdown    = require('metalsmith-markdown'),
    partials    = require('metalsmith-register-partials');

// Handlebars.registerPartial('header', fs.readFileSync(__dirname + '/templates/partials/header.hbt').toString());
// Handlebars.registerPartial('footer', fs.readFileSync(__dirname + '/templates/partials/footer.hbt').toString());

Metalsmith(__dirname)
    .use(partials({
        directory: 'templates/partials'
    }))
    .use(markdown())
    .use(templates('handlebars'))
    .destination('./build')
    .build(function(err,files){
        if (err){ console.log(err); }
    })
```

I'm sort of new to Node, and very new to Metalsmith and Handlebars, but - I assume this is because the Handlebars imported by metalsmith-register-partials is the module's locally installed one, but it should be the global one / the one that all other Metalsmith plugins are using?

Manually registering the partials in the metalsmith script file works ( the 2 commented out lines ) and Metalsmith completes the build successfully.

This plugin is definitely loading and registering my partials on the Handlebars it loads, and using the same names as the manual registration. They're just not available when Metalsmith tries to render the templates later. When I modify this plugin to manually register my 'header' and 'footer' templates ( which works in the main script ), the problem persists - supporting this idea.

Any thoughts on the best way to resolve this issue? Editing this plugin to assume a global Handlebars instance doesn't seem right. Googling this Handlebars error is just turning up stuff like 'be sure to register your partials' and 'dashes and spaces are turned into underscores', which are definitely not the problem.

**Comment by linclark** [comment]
I think I understand the issue here. Can you try running `npm dedupe`? If that doesn't work, can you copy the version of Handlebars that you're using in your application's `package.json`?

**Comment by iabw** [comment]
I did not know about dedupe! That seems to have solved the problem. Thanks Lin.

**Comment by linclark** [comment]
np, glad it worked!

**Comment by OscarF** [comment]
I am having the same problem. `npm dedupe` didn't work.
Is there a more solid way of adding partials?

**Comment by linclark** [comment]
Not that I know of. I developed this for my own use case, so I can't say for sure.

**Comment by iabw** [comment]
@OscarF Just in case this helps - After I deduped, handlebars was no longer in the installed `node_modules` for metalsmith-register-partials. I'd check that it's actually been removed by dedupe, and then if it hasn't, try adding it as a dependency of your root project that requires metalsmith and metalsmith-register-partials and running dedupe again.

If dedupe worked and you're still getting this error, I would say it's gotta be a problem with how you're referencing the directory.
